name: Step 1, Make a workflow reusable

# This step triggers after the learner pushes a commit to `reusable-workflow`
# This step sets STEP to 2
# This step closes <details id=1> and opens <details id=2>

# This will run every time we push a commit to `reusable-workflow`
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - reusable-workflow

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  make_reusable_workflow:
    name: Make reusable workflow

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      # Verify the learner added the file contents
      - name: Check workflow contents, workflow call
        run: ./.github/script/check-file.sh
        env:
          FILE: ".github/workflows/reusable-workflow.yml"
          SEARCH: "workflow_call:"

      # Update README to close <details id=1> and open <details id=2>
      # and set STEP to '2'
      - name: Update to step 2
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
          branch_name: reusable-workflow
